### ISSUE TITLE
Disable netdata local emails

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/ansible-playbooks#59]
I am getting emails from both netdata cloud and local DNP installed netdata instances.

**Comment by thomasbeaudry** [comment]
I'm not, are you getting 2 emails per alarm?  Maybe it's because you are both sitemgr and admin?

**Comment by gdevenyi** [comment]
Its because I'm configured as the "root" account on all systems, so the local netdata is sending email to root, which ends up forwarded to my gmail.

**Comment by gdevenyi** [comment]
https://learn.netdata.cloud/docs/alerting/notifications/agent-dispatched-notifications/email

**Comment by thomasbeaudry** [comment]
I saw that yesterday and was thining about doing an ansible inline subsitution for the health file, but I wanted to modifying our netdata.conf file first (since it follows a template).  On CICWs45 i change the health section to:

[health]
  enabled alarms = !used_swap !ram_available *
  DEFAULT_RECIPIENT_EMAIL=""

And then I sent out a test warning at 2:09pm from cicws45.  I wanted to know if you got 2 emails for it or just 1?

Also, is it just the critical emails that you get 2 of, or all of them?

**Comment by thomasbeaudry** [comment]
fixed with: https://github.com/DouglasNeuroInformatics/ansible-playbooks/pull/62
